# action.yml
name: "Docker Build and Push Dev Images"
description: "Builds the Docker image and pushes it to the specified registry"
inputs:
  registry:
    description: "Registry's host"
    required: true
    default: "ghcr.io"
  user:
    description: "Registry's user"
    required: true
  password:
    description: "Registry user's password or token"
    required: true
  image:
    description: "Docker image name without tag"
    required: true
  tag:
    description: "Docker image tag"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Gitlab Registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.user }}
        password: ${{ inputs.password }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3.6.1
      with:
        images: ${{ inputs.image }}

    - name: Build and push -dev image
      uses: docker/build-push-action@v2.7.0
      with:
        context: ${{ github.workspace }}
        cache-from: ${{ inputs.image }}:${{ inputs.tag }}
        platforms: linux/amd64
        push: true
        build-args: |
          DEV=yes
        tags: |
          ${{ inputs.image }}:${{ inputs.tag }}-dev
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push prod image
      uses: docker/build-push-action@v2.7.0
      with:
        context: ${{ github.workspace }}
        cache-from: ${{ inputs.image }}:${{ inputs.tag }}
        platforms: linux/amd64
        push: true
        build-args: |
          DEV=no
        tags: |
          ${{ inputs.image }}:${{ inputs.tag }}
        labels: ${{ steps.meta.outputs.labels }}
