name: Deploy Docker Image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - development
      - master
      - production
    types:
      - closed

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy_to_servers:
    name: Deploy Docker image to servers
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          config: |
            Host *
              VerifyHostKeyDNS no
              StrictHostKeyChecking no
          if_key_exists: ignore

      - name: Deploy testing
        if: github.ref == 'refs/heads/development'
        run: |
          ./deploy/deploy.sh testing development --force

      - name: Deploy staging
        if: github.ref == 'refs/heads/master'
        run: |
          ./deploy/deploy.sh staging master --force

      - name: Deploy production
        if: github.ref == 'refs/heads/production'
        run: |
          ./deploy/deploy.sh production production --force

      - name: Deploy korea
        if: github.ref == 'refs/heads/production'
        run: |
          ./deploy/deploy.sh korea production --force
